spring:
  application:
    name: "bloggio-api"
  datasource:
    url: ${URL_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8085
bloggio:
  app:
    jwtSecret: "bloggioSecretKey"
    jwtExpirationMs: 86400000
    base-url : "https://bloggio-web.onrender.com"

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

sendgrid:
  api-key: ${SENDGRID_API_KEY}

#logging:
#  level:
#    #root: "warn"
#    org.springframework.web: "info"
#    org.hibernate: "error"
