spring:
  application:
    name: "bloggio-api"
  datasource:
    url: jdbc:postgresql://dpg-cq51a6dds78s73cqojfg-a.oregon-postgres.render.com/bloggio_dd7x
    username: bloggio_dd7x_user
    password: bM0Y3cka8pzZDXRC21rMsyrHXwaIcCiQ
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
bloggio:
  app:
    jwtSecret: "bloggioSecretKey"
    jwtExpirationMs: 86400000
cloudinary:
  cloud_name: "dbxivsisb"
  api_key: "559448955182318"
  api_secret: "nzq94PvMyd1AGVyVSE36RATj69w"